version: "3"
services:
  reverseproxy:
    network_mode: "host"
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  backend_user:
    network_mode: "host"
    build:
      context: ./udagram-api-user
    image: udagram-api-user
  backend_feed:
    network_mode: "host"
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
  frontend:
    network_mode: "host"
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local