apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      restartPolicy: Always
      containers:
        - name: udagram-reverseproxy
          imagePullPolicy: Always
          image: smailbou/udagram-reverseproxy
          ports:
            - containerPort: 8080
