apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: udagram-reverseproxy